on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* 1 * * *' # every day
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data from the API endpoint
      run: |-
        curl -s "https://innatcedarfalls.com/" > campaign.html
    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
